// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:2bd9f054-d131-4534-9f54-ef084fafd667';
var aws_cognito_region = 'us-east-1';
var aws_mobile_analytics_app_id = '9e12346d15ab43b19e153cd08d38d7e2';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '0b351dfc-53ff-45a6-a72a-f53eceba3221';
var aws_project_name = 'myApp';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'myapp-mobilehub-231222231';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
